name: CI DEV Test

on:
  push:
    branches: ["feat/*/*"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.1, 8.2]
        laravel: [9.*, 10.*]
        include:
          - php: 7.3
            laravel: 5.8.*
          - php: 7.3
            laravel: 6.*
          - php: 7.4
            laravel: 7.*
          - php: 7.4
            laravel: 8.*

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo, sqlite, pdo_sqlite

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: |
          composer config --no-plugins allow-plugins.kylekatarnls/update-helper true
          composer require "laravel/framework:${{ matrix.laravel }}" --no-update
          composer update

      - name: Execute tests
        run: |
          vendor/bin/phpunit
