name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name : Checkout code
      uses: actions/checkout@v3
      
    - name : Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: pdo, sqlite, pdo_sqlite

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: vendor/bin/phpunit
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
