name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        #php: [ 8.1, 8.2 ]
        #laravel: [ 9.*, 10.* ]
        include:
          - php: 7.3
            laravel: 5.7.*
            testbench: 3.*
          #- php: 7.3
          #  laravel: 5.8.*
          #- php: 7.3
          #  laravel: 6.*
          #- php: 7.4
          #  laravel: 7.*
          #- php: 7.4
          #  laravel: 8.*
        

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
    - name : Checkout code
      uses: actions/checkout@v3
      
    - name : Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: pdo, sqlite, pdo_sqlite

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" --no-update
        composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-update
        composer update

    - name: Execute tests with PHPUnit 8 or below
      if: ${{ matrix.laravel == '5.7.*' || matrix.laravel == '5.8.*' }}
      run: vendor/bin/phpunit -c ./phpunit8.xml --coverage-clover=coverage.xml

    - name: Execute tests
      if: ${{ matrix.laravel != '5.7.*' && matrix.laravel != '5.8.*' }}
      run: vendor/bin/phpunit --coverage-clover=coverage.xml
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
          name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
          files: coverage.xml
